--Magnitude Exploration -> comparing measure values by categories

--Finding total customers by country

Select country, Count(customer_key) as Number_of_Customers
from gold.dim_customers
group by country
order by Number_of_Customers desc;

--Total Customers by Gender
Select gender, Count(customer_key) as Number_of_Customers
from gold.dim_customers
group by gender
order by Number_of_Customers desc;

--Total Products by Category
Select category, Count(product_key) as Number_of_Products
from gold.dim_products
group by category
order by Number_of_Products desc;

--Average cost in each Category
Select category, Avg(Cost) as Average_Cost
from gold.dim_products
group by category
order by Average_Cost desc;

--Total Revenue Generated by each category
Select p.category, Sum(s.sales_amount) as TotalRevenue
from gold.fact_sales s left join gold.dim_products p on p.product_key = s.product_key
group by p.category
order by TotalRevenue desc;

--Total Revenue by customer
Select c.customer_key,c.first_name,c.last_name, Sum(s.sales_amount) as TotalRevenue
from gold.fact_sales s left join gold.dim_customers c on c.customer_key = s.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by TotalRevenue desc;

--Distribution of Sold items accross countries
Select c.country, SUM(s.quantity) as Product_Sold
from gold.fact_sales s join gold.dim_customers c on c.customer_key = s.customer_key
group by c.country
order by Product_Sold desc;